Custom Serve and Error Handler for Services
MrToino/MPB pull request #16
Opened 2022-08-02 22:42 UTC by MrToino

The purpose of this component is to implement a custom MPB server handler, to be used on all services. Some error handlers will also be included in this custom server.

2022-08-03 12:58 UTC, luisferreira32 requested changes

2022-08-03 12:58 UTC, luisferreira32 commented on intmodules/log.py
> +log_path = "..\\services\\logs\\"
Don't do this, windows vs unix systems will break. use a path join or sth like that

2022-08-03 12:58 UTC, luisferreira32 commented on intmodules/__init__.py
> +from intmodules.log import logger
```suggestion
from intmodules.log import config_logger, logger
```

2022-08-03 13:19 UTC, MrToino commented on intmodules/__init__.py
> +from intmodules.log import logger
You are right. I was following some good practices (https://aglowiditsolutions.com/blog/python-best-practices/). 
In fact, having multiple "from ____ import ____" it is okay to put it all in one same line. Having multiple "import ____" we must leave them in different lines. I will make the change, in this case.

2022-08-03 21:18 UTC, MrToino commented
Server handler related changes will be implemented on another [PR](https://github.com/MrToino/MPB/pull/17). 
This pull request will await the completeness of the prior request.

2022-08-11 21:12 UTC, luisferreira32 approved these changes
Once again this PR files changed are all broken... another way to try to avoid this could also be reset all commits (soft reset), stash them, rebase from main, then unstash, solve conflicts and voilá create your own new commit 👍

2022-08-11 23:48 UTC, merged