Added multiple options suppport
MrToino/MPB pull request #33
Opened 2022-10-13 23:05 UTC by MrToino

Added support for multiple plotting options in the backend.

2022-10-14 21:50 UTC, luisferreira32 requested changes
Still some work to do. Going in the right direction though.

2022-10-14 21:50 UTC, luisferreira32 commented on application/src/components/FitterTab.tsx
> +    color: "#0000FF",
Instead of having this part repeated I'd create a `defaultOptions` exported object that you could import when using the `options` state. Unless you prefer to have them separate? I could see arguments for both sides

2022-10-14 21:50 UTC, luisferreira32 commented on services/plotter/parser.py
> +    with open(".\services\plotter\schema.json") as f:
This should not live here, nor should we need to do i/o read for every request happening. The loads should happen once when the server starts up, and either you pass it as an argument for this function (my preferred way) or create a parser "client" that will hold this state and function.

2022-10-14 21:50 UTC, luisferreira32 commented on services/plotter/plotter.py
> +    plt.xlabel(xlabel=configs["xlabel"]["xlabel"], loc=configs["xlabel"]["loc"])
I know "color" and "loc" is are strings, but they are not really free format strings. They're more like an enum (fixed number of values) so we need to do some serious type checking here if we don't want this to fail (it's user input anyway).
My proposal:
1. Front-end can treat it as a string, but only accepts if it conforms to the N possibilities
2. Back-end treats it as an enum with the fixed number of values (also returns bad request if it's not "castable "to the enum since converting invalid int would actually give an exception)

2022-10-14 21:52 UTC, MrToino commented on application/src/components/FitterTab.tsx
> +    color: "#0000FF",
As a matter of POC, both services are now accepting the same options, however, the options will be different in the future. In our case, I guess that having them separated will be better.

2022-10-14 21:58 UTC, MrToino commented on services/plotter/parser.py
> +    with open(".\services\plotter\schema.json") as f:
You are right, this is a fixed schema that must be validated at the service level.  I believe we can save this object as an argument of the server object itself, which is loaded whenever the server starts, i.e., this schema could come as an argument for the service handler object. However, I think this could kinda violate the Single Responsibility Principle. What do you think about this?

2022-10-14 22:04 UTC, MrToino commented on services/plotter/plotter.py
> +    plt.xlabel(xlabel=configs["xlabel"]["xlabel"], loc=configs["xlabel"]["loc"])
Yes i agree. Notice that this PR is just a POC to see how can we deal with options.
For later development, we should first establish what are the real features that we want to implement. I believe that front-end should do the checking. Regarding back-end, the better practices would be:
1. use ".get" instead of directly calling the dictionary key itself, and make use of the default values in case of any error
2. not exactly throw a bad-request, but a simple warning for "invalid option" would be enough
But once again, this is just a POC, that must be changed in the future, however, the options definition is firstly required.

2022-10-14 22:13 UTC, luisferreira32 commented on application/src/components/FitterTab.tsx
> +    color: "#0000FF",
All right, separated it is for now :+1:

2022-10-14 23:16 UTC, luisferreira32 commented on services/plotter/parser.py
> +    with open(".\services\plotter\schema.json") as f:
So someone has to have the knowledge of it, and that has to be started in the main process. You either:
1. Load it into the handler (saving the state there) and pass it onto the service call
2. Load it into a parser "client", and pass a reference for the handler to use this parser client

The parsing responsibility is still on the parsing function / client. You just have to get a config there.

2022-10-14 23:38 UTC, MrToino commented on services/plotter/parser.py
> +    with open(".\services\plotter\schema.json") as f:
Okay that's what I was thinking. I guess we will stick with the first option.

2022-10-14 23:41 UTC, luisferreira32 commented on services/plotter/plotter.py
> +    plt.xlabel(xlabel=configs["xlabel"]["xlabel"], loc=configs["xlabel"]["loc"])
1. Not really related with the initial comment (another discussion altogether)
2. "invalid option" in http responses doesn't exist. either you ignore the field and continue the rest of the request, or throw in a bad request (i.e. invalid arguments/option)

2022-10-15 15:25 UTC, luisferreira32 approved these changes
I don't have the patience to see the diff, but good luck!

2022-10-15 15:28 UTC, MrToino commented on services/plotter/plotter.py
> +    plt.xlabel(xlabel=configs["xlabel"]["xlabel"], loc=configs["xlabel"]["loc"])
Yes, I understand and I agree with your point. But I guess this error handling can be treated on another PR.
Nevertheless, I will accept your suggestion and throw an error whenever an option is not among the valid options.

2022-10-15 15:30 UTC, merged